from typing import Protocol
from src.domain.book import Book


class BookRepositoryProtocol(Protocol):
    def get_all_books(self) -> list[Book]: ...

    def add_book(self, book: Book | list[Book]) -> str | list[str]: ...

    def find_book_by_name(self, query) -> list[Book]: ...

    def delete_book(self, book_id: str) -> bool: ...

    def update_book(self, book_id: str, data: dict) -> bool: ...
